import { AppSidebar } from "@/components/app-sidebar";
import NavBreadcrumb from "@/components/nav-breadcrumb";
import { Separator } from "@/components/ui/separator";
import {
    SidebarInset,
    SidebarProvider,
    SidebarTrigger,
} from "@/components/ui/sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const SidebarLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <SidebarProvider>
            <AppSidebar />
            <SidebarInset className="p-2 max-h-screen bg-[#f4f4f4] w-full">
                <main className="h-full flex flex-col overflow-hidden rounded-lg border bg-white shadow">
                    <header className="flex border-b h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                        <div className="flex items-center gap-2 px-4">
                            <SidebarTrigger className="-ml-1" />
                            <Separator
                                orientation="vertical"
                                className="h-4 mr-2"
                            />
                            <NavBreadcrumb />
                        </div>
                    </header>
                    <div className="flex flex-1 flex-col overflow-y-scroll p-4 pt-0 scrollbar-thin">
                        <div className="flex-1">{children}</div>
                    </div>
                </main>
            </SidebarInset>
        </SidebarProvider>
    );
};

export default SidebarLayout;
