// import { AppSidebar } from "@/components/app-sidebar";
// import FinalItemCard from "@/components/catering/final-item-card";
// import NavBreadcrumb from "@/components/nav-breadcrumb";
// import { Button } from "@/components/ui/button";
// import { Separator } from "@/components/ui/separator";
// import {
//     SidebarInset,
//     SidebarProvider,
//     SidebarTrigger,
// } from "@/components/ui/sidebar";
// import { Metadata } from "next";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// const SidebarLayout = ({ children }: { children: React.ReactNode }) => {
//     return (
//         <SidebarProvider>
//             <AppSidebar />
//             <SidebarInset className="p-2 max-h-screen bg-[#f4f4f4] w-full">
//                 <main className="h-full flex flex-col overflow-hidden rounded-lg border bg-white shadow">
//                     <header className="flex border-b h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
//                         <div className="flex items-center gap-2 px-4">
//                             <SidebarTrigger className="-ml-1" />
//                             <Separator
//                                 orientation="vertical"
//                                 className="h-4 mr-2"
//                             />
//                             <NavBreadcrumb />
//                         </div>
//                     </header>
//                     <div className="flex flex-1 overflow-y-scroll p-4 pt-0 scrollbar-thin">
//                         <div className="flex-1">{children}</div>
//                         <div className="flex flex-col h-full max-h-[calc(100vh-64px)] p-4 bg-white border shadow-sm w-80 rounded-xl">
//                             <h2 className="text-lg font-semibold">
//                                 Selected Items
//                             </h2>
//                             <div className="flex-1 py-3 space-y-4 overflow-y-scroll scrollbar-thin">
//                                 <FinalItemCard />
//                                 <FinalItemCard />
//                             </div>
//                             <div className="flex justify-end">
//                                 <Button>Confirm Order</Button>
//                             </div>
//                         </div>
//                     </div>
//                 </main>
//             </SidebarInset>
//         </SidebarProvider>
//     );
// };

// export default SidebarLayout;

import * as React from "react";
import CssBaseline from "@mui/material/CssBaseline";
import Box from "@mui/material/Box";
import AppNavbar from "@/components/dashboard/app-navbar";
import SideMenu from "@/components/dashboard/sidemenu";
import MuiThemeProvider from "@/providers/mui-theme-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import connectDB from "@/lib/mongodb";
import Store from "@/models/storeModel";

export default async function DashboardLayout(
    { children }: { children: React.ReactNode },
    props: { disableCustomTheme?: boolean }
) {
    const session = await getServerSession(authOptions);

    if (
        !session?.user.id ||
        (!session?.user.storeId && session?.user.role !== "SUPERADMIN")
    )
        return null;

    await connectDB();
    const store = await Store.findById(session.user.storeId);

    return (
        <MuiThemeProvider props={props}>
            <CssBaseline enableColorScheme />
            <Box sx={{ display: "flex" }}>
                <SideMenu />
                <AppNavbar
                    role={session.user.role}
                    username={session.user.username}
                    location={store.location}
                />
                {/* Main content */}
                {children}
            </Box>
        </MuiThemeProvider>
    );
}
